name: nextjs

ssh:
  username: iop

# Unified services model - everything is a service!
# Services with 'proxy' config get zero-downtime deployment automatically
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV
        - NEXT_PUBLIC_API_URL
    server: 157.180.25.101
    environment:
      plain:
        - NODE_ENV=production
        - NEXT_PUBLIC_API_URL=https://api.example.com
    proxy:           # This triggers zero-downtime deployment
      #hosts:
      #  - nextjs.example.myiop.cloud
      app_port: 3000
