name: basic-test

ssh:
  username: iop

# Test with services that have identical build configurations  
services:
  # Both services use identical build context and args
  web1:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - EXAMPLE_VAR
    server: 157.180.47.213
    replicas: 1
    environment:
      plain:
        - EXAMPLE_VAR=same  # Same value for both services
      secret:
        - SECRET_VAR
        - POSTGRES_PASSWORD
    proxy:
      app_port: 3000
    health_check:
      path: /up

  web2: 
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - EXAMPLE_VAR
    server: 157.180.47.213
    replicas: 1
    environment:
      plain:
        - EXAMPLE_VAR=same  # Same value for both services
      secret:
        - SECRET_VAR
        - POSTGRES_PASSWORD
    proxy:
      app_port: 3000
    health_check:
      path: /up

  # Infrastructure service
  db:
    image: postgres:17
    server: 157.180.47.213
    ports:
      - "5433:5432"
    environment:
      plain:
        - POSTGRES_USER=postgres
        - POSTGRES_DB=postgres
      secret:
        - POSTGRES_PASSWORD
    volumes:
      - ./pgdata:/var/lib/postgresql/data